### ISSUE TITLE
Wait() should return normally if the child process has already terminated

### ISSUE THREAD

**Issue by reynir** [pexpect/ptyprocess#13]
Calling `wait()` on a PtyProcess object whose process has already terminated will raise an exception. This behavior is unexpected[1].
I have made a small [test](https://gist.github.com/reynir/6616b43999449f26d299) to show case the behavior. Using `p.isalive() && p.wait()` will only make the race condition worse in my tests.

[1]: subprocess.Popen.wait() returns normally even when the process has already terminated, although it doesn't say so explicitly in the documentation. In [java](http://docs.oracle.com/javase/7/docs/api/java/lang/Process.html#waitFor%28%29) the `waitFor()` method *"returns immediately if the subprocess has already terminated."*

**Comment by reynir** [comment]
Maybe more importantly this is not the behavior of `expect(1)`

**Comment by jquast** [comment]
agreed, fix + test case would be accepted.

**Comment by takluyver** [comment]
I agree, but we should be careful with Pexpect, because this is its historical behaviour, and I don't think it's worth breaking backwards compatibility to change that. For ptyprocess, which is a new API, it absolutely makes sense to follow conventions more, though.

**Comment by reynir** [comment]
Thanks for acknowledging.

**Comment by jquast** [comment]
Became PR #18, and in pexpect, https://github.com/pexpect/pexpect/pull/211

Lets allow those open PR's to address any further comments and close this one. Thanks again @reynir !
