### ISSUE TITLE
Logging of stdout and stderr

### ISSUE THREAD

**Issue by JohnLonginotto** [pexpect/ptyprocess#27]
Hi :)

I would like to subprocess any given command and log its stdout and stderr separately. This would seem like an easy thing to do, but im having no luck because:
1) Processes which detect that their stdout/stderr are not ttys will modify their output
2) Processes which detect that their stdout/stderr are not the same file path will assume theres stdout redirection and modify their output.

So in jumps ptys and ptyprocess to the resuce. Tie the stdout and stderr to a pty, you get 1 file path like  /dev/tty0021, and isatty() returns true for both. Problem is - now we can't distinguish stdout from stderr.
Ok, no problem, just make two ptys - one for stdout and one for stderr. But now although both pass isatty(), their file paths will now look like /dev/tty0021 and /dev/tty0022 (for example).
The subprocess reacts as if you weren't using a pty in the first place, and you log nothing.

I have been trying for four months to figure a way around this, and because you are the expert in ptys I thought i might ask you directly - could you think of a way to log stdout and stderr separatly in your program, and still fool a script like this: https://bpaste.net/show/000d6f70ef41

THANK YOU :D

**Comment by takluyver** [comment]
I think it depends on the subprocess you're targeting. I think most things that want to do tty detection just pick one of the stdstreams and check isatty(). Checking that they have the same name seems pathological.

If you really need to deal with something that checks that, and you can't modify the code of that thing, you may be able to fool it with some LD_PRELOAD hacks, but I have no experience of that.

I'm not the expert in ptys - [this guy is](http://www.linusakesson.net/programming/tty/index.php) ;-)

**Comment by JohnLonginotto** [comment]
Hahah, yeah maybe i should ask him too - i read the guide, but all it did was cement the idea in my head that its not going to be possible :P
And whilst i totally agree that checking if they have the same name is a terribly unnecessary idea, it's some how crept its way into a bunch of shared libs like this: http://src.gnu-darwin.org/src/bin/stty/util.c
which are used by other processes which just want to know 'isatty()'? and this sort of code returns 'nope.'
Sucks :(

**Comment by takluyver** [comment]
Yeah, there's not a lot you can do for something like that. Can you
sacrifice the separation of stdout and stderr? Other than that, the only
thing I can think to try is the LD_PRELOAD hack, but as I mentioned, I've
never tried to do that,  and I wouldn't really want to.

**Comment by JohnLonginotto** [comment]
Yup, I think you are right and either you sacrifice splitting of stdin/out/err, or, you LD_PRELOAD to modify the program doing the checks, which is extremely flakey.
Another approach would be to use strace/DTrace to read the writes at the kernel level, but a'int no one got time fo' that.

You can probably close this "issue", but if i ever find a solution I will let you know :)

**Comment by takluyver** [comment]
Thanks John - good luck

**Comment by pawamoy** [comment]
@JohnLonginotto, @takluyver  not sure to understand, would using two ptys work? One for stdout and one for stderr? If yes, is it possible with the current state of `ptyprocess`?
