### ISSUE TITLE
A minor issue found via static analysis

### ISSUE THREAD

**Issue by tzickel** [pexpect/ptyprocess#35]
ExceptionPexpect is not defined.
https://github.com/pexpect/ptyprocess/blob/8f1ba73b82a4b4fbe342fef1498cd35362f63982/ptyprocess/_fork_pty.py#L66

Found using cython and
https://gist.github.com/tzickel/ea4541b12c1298a8092c3ec5043ef77e
```
pip install -I --root temp_ptyprocess ptyprocess
python checkcython.py temp_ptyprocess
```

**Comment by takluyver** [comment]
Thanks! #36 should fix it.
