### ISSUE TITLE
pty cannot read unicode color escapde

### ISSUE THREAD

**Issue by demonguy** [pexpect/ptyprocess#70]
My company has a ssh server, which would return QR code (by sending unicode and color escape), show in screenshot.
```
ssh xxxx@relay.office.com
```
![6745260651f884d271e43d82d88331c](https://user-images.githubusercontent.com/1451096/152732949-6744e2f4-16df-4972-9022-1d1339ccac88.jpg)

the intact output of ssh session is in the attachment `ssh_output.log`

However if i tried to use ptyprocess to read it , it just read the first 3 bytes and then hangs forever.
```
#!/usr/bin/env python
import ptyprocess

p = ptyprocess.PtyProcess.spawn(["/usr/bin/ssh", "chengyang@relay.office.com"])
s = p.read(1000)
print(s)  # this line return b'\x1b[c'
s = p.read(1000) # this line blocks forever
```
![84b2acaced1385873c02b695b5b2376](https://user-images.githubusercontent.com/1451096/152733776-a5123233-5f1d-494c-af43-2a1b1d63b3a7.jpg)

Why would this happen and how can i solve it?

[ssh_output.log](https://github.com/pexpect/ptyprocess/files/8012779/ssh_output.log)

**Comment by jquast** [comment]
You need to reply to this sequence, "CSI Ps c  Send Device Attributes (Primary DA)." https://gist.github.com/justinmk/a5102f9a0c1810437885a04a07ef0a91#file-xterm-control-sequences-txt-L356

Test it yourself in shell `printf "\033[c"`, or python repl, `print('\033[c')`. My terminal replies "\033[?62;4c" which means "VT420 with Sixel graphics"

**Comment by demonguy** [comment]
That's new to me. Thanks
